export const BUSINESS_LINES = {
  ecommerce: {
    label: "E-commerce / Retail",
    journey: [
      "Discovery & Search",
      "Product Selection",
      "Cart & Checkout",
      "Payment",
      "Order Placement",
      "Fulfillment & Delivery",
      "Returns & Refunds",
      "Post-purchase Support",
    ],
    categories: [
      "Account",
      "Order & Fulfillment",
      "Payment & Checkout",
      "Returns & Refunds",
      "Product",
      "Website/App UX",
      "Customer Support",
      "Pricing & Promotions",
    ],
  },
  hospital: {
    label: "Hospital / Healthcare",
    journey: [
      "Booking & Appointment",
      "Check-in & Registration",
      "Consultation",
      "Diagnostics & Treatment",
      "Billing & Insurance",
      "Discharge / Check-out",
      "Follow-up Care",
    ],
    categories: [
      "Appointment & Scheduling",
      "Reception & Admin",
      "Clinical Care",
      "Diagnostics",
      "Billing & Insurance",
      "Facilities & Hygiene",
      "Staff Behaviour",
      "Digital / App Experience",
    ],
  },
  banking: {
    label: "Banking & Financial Services",
    journey: [
      "Onboarding & KYC",
      "Account Servicing",
      "Transactions & Payments",
      "Lending & Credit",
      "Dispute & Fraud",
      "Closure / Offboarding",
    ],
    categories: [
      "Account & Onboarding",
      "Transactions & Payments",
      "Cards",
      "Loans & Credit",
      "Fees & Charges",
      "Fraud & Disputes",
      "Digital Banking UX",
      "Customer Support",
    ],
  },
  telecom: {
    label: "Telecom",
    journey: [
      "Plan Discovery",
      "Activation & Porting",
      "Usage & Network",
      "Billing & Recharge",
      "Support & Troubleshooting",
      "Cancellation",
    ],
    categories: [
      "Network & Coverage",
      "Plans & Pricing",
      "Billing & Recharge",
      "Activation & Porting",
      "Device & SIM",
      "App / Self-service UX",
      "Customer Support",
    ],
  },
  travel: {
    label: "Travel & Hospitality",
    journey: [
      "Search & Discovery",
      "Booking",
      "Pre-trip / Check-in",
      "In-stay / In-journey",
      "Check-out",
      "Cancellation & Refunds",
      "Loyalty & Follow-up",
    ],
    categories: [
      "Booking Experience",
      "Pricing & Fees",
      "Check-in / Check-out",
      "Room / Seat Quality",
      "Food & Amenities",
      "Staff & Service",
      "Cancellations & Refunds",
      "App / Website UX",
    ],
  },
  saas: {
    label: "SaaS / Software",
    journey: [
      "Evaluation & Trial",
      "Onboarding & Setup",
      "Daily Usage",
      "Integrations",
      "Billing & Subscription",
      "Support",
      "Renewal / Churn",
    ],
    categories: [
      "Onboarding",
      "Core Features",
      "Performance & Reliability",
      "Integrations & API",
      "Billing & Subscription",
      "UI/UX",
      "Documentation",
      "Customer Support",
    ],
  },
} as const;

export type BusinessLineKey = keyof typeof BUSINESS_LINES;
export const BUSINESS_LINE_KEYS = Object.keys(BUSINESS_LINES) as BusinessLineKey[];
export const FALLBACK_CATEGORY = "Other/Uncategorized";
